package(default_visibility = ["//visibility:public"])

# Connection libraries
cc_library(
    name = "credit",
    hdrs = ["credit.h"],
)

cc_library(
    name = "link",
    hdrs = ["link.h"],
)

cc_library(
    name = "ready_valid",
    hdrs = ["ready_valid.h"],
)

cc_library(
    name = "regf_wire",
    hdrs = ["regf_wire.h"],
)

cc_library(
    name = "wire",
    hdrs = ["wire.h"],
)
